const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"舱位管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryCangwei"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"飞机票类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryFeijipiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"航班管理动态类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHangbanguanlidongtai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"会员等级类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryHuiyuandengji"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"使用帮助类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShiyongbangzhu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"出发地管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryChufadi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"目的地管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryMudidi"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"飞机票管理",
                        "menuJump":"列表",
                        "tableName":"feijipiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"飞机票评价管理",
                        "menuJump":"列表",
                        "tableName":"feijipiaoCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"飞机票收藏管理",
                        "menuJump":"列表",
                        "tableName":"feijipiaoCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看",
                            "删除"
                        ],
                        "menu":"飞机票购买订单管理",
                        "menuJump":"列表",
                        "tableName":"feijipiaoOrder"
                    }
                ],
                "menu":"飞机票管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"航班管理动态管理",
                        "menuJump":"列表",
                        "tableName":"hangbanguanlidongtai"
                    }
                ],
                "menu":"航班管理动态管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"使用帮助管理",
                        "menuJump":"列表",
                        "tableName":"shiyongbangzhu"
                    }
                ],
                "menu":"使用帮助管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"客户管理",
                        "menuJump":"列表",
                        "tableName":"kehu"
                    }
                ],
                "menu":"客户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"飞机票管理",
                        "menuJump":"列表",
                        "tableName":"feijipiao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"飞机票评价管理",
                        "menuJump":"列表",
                        "tableName":"feijipiaoCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"飞机票收藏管理",
                        "menuJump":"列表",
                        "tableName":"feijipiaoCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "查看"
                        ],
                        "menu":"飞机票购买订单管理",
                        "menuJump":"列表",
                        "tableName":"feijipiaoOrder"
                    }
                ],
                "menu":"飞机票管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"航班管理动态管理",
                        "menuJump":"列表",
                        "tableName":"hangbanguanlidongtai"
                    }
                ],
                "menu":"航班管理动态管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"使用帮助管理",
                        "menuJump":"列表",
                        "tableName":"shiyongbangzhu"
                    }
                ],
                "menu":"使用帮助管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"客户",
        "tableName":"kehu"
    }
]
    }
}
export default menu;
